apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chatapp

spec:
  type: NodePort   # optional but useful for direct access

  selector:
    app: frontend   # MUST match your deployment labels

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
