kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
  namespace: chatapp

spec:
  selector:
    app: mongodb

  ports:
    - port: 27017
      targetPort: 27017

  clusterIP: None   # optional (headless for DB)
