kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    app: mongodb   # ✅ Added label (BEST PRACTICE)

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: local-storage

  hostPath:
    path: /mnt/data   # ⚠️ DEV ONLY (not for production)
