kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  namespace: chatapp
  labels:
    app: mongodb   # ✅ Added label

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-storage

  resources:
    requests:
      storage: 5Gi

  volumeName: mongodb-pv   # ✅ Static binding (OK for dev)
