kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  namespace: chatapp
type: Opaque

# ❌ YOU USED base64 JWT → not correct usage
# ❌ JWT should NOT be stored

# ✅ Use stringData instead
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: strongpassword123
  JWT_SECRET: supersecretkey
